name: Package custom godot

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest
    container:
      image: docker.io/razoric480/godot-learn-builder:1.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile godot
        run: |
          chmod +x ./compile_for_learn_gdscript.sh
          ./compile_for_learn_gdscript.sh

      - name: Prepare release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GODOT_VERSION=$(python -c "import pathlib; ns={}; \
            exec(pathlib.Path('version.py').read_text(), ns); \
            print(f\"{ns['major']}.{ns['minor']}.{ns['patch']}\")")

          gh release delete "$GODOT_VERSION" -y || true
          gh release create "$GODOT_VERSION" \
            --title "Godot Learn ${GODOT_VERSION}" \
            --notes "Automated release for ${GODOT_VERSION}"
          gh release upload "$GODOT_VERSION" \
            bin/godot-learn.${GODOT_VERSION}.zip#Compiled_Bins
